# using version 3 of the docker-compose API
version: '3'

# there is only one service for the plugin
services:

  # service to publish the created plugin to NPM registries
  node:
    # builds the Dockerfile from the current folder
    build: .
    # mounting local folders into the container
    volumes:
      - .:/home/node/rollup-plugin-generate-html
    # prevent the container from stoping after being up
    stdin_open: true
    # allow the use of commands inside the container
    tty: true
