# using version 3 of the docker-compose API
version: '3'

# there is only one service for the plugin
services:

  # service to publish the created plugin to NPM registries
  node:
    # builds the Dockerfile from the current folder
    build: .
    # mounting local folders into the container
    volumes:
      - ./src:/home/node/src
      - ./dist:/home/node/dist
